apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-dep
  labels:
    app: spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: spring
        ports:
        - containerPort: 70
